### ISSUE TITLE
Optional Usage of juce_VSTInterface.h

### ISSUE THREAD

**Issue by mfisher31** [DISTRHO/juce#16]
It is convenient to have this header, but some users might prefer using the real VST2 SDK.  I'm working on this here, and just need to test it actually works:

https://github.com/kushview/JUCE_distrho/commit/f43614798ecf6f275f4417887b59067bfb5728bc

**Comment by falkTX** [comment]
VST2 SDK is incompatible with GPL, so I have no interest on it.

**Comment by mfisher31** [comment]
I don't understand why it matters. You haven't removed support for AAX.

**Comment by falkTX** [comment]
It matters because using the vst2 sdk is a LOT of changes.
See https://github.com/DISTRHO/DISTRHO-Ports/blob/master/libs/juce-current/patches/04_vst2-interface.patch

I do not want to maintain this more than just keeping the old juce code.

Plus there is no AAX code inside juce that I know, so there is no GPL violation there.
This juce fork as described in the README is intended for GPL projects only.

**Comment by mfisher31** [comment]
Ah ok, I thought it was just a simple header swap.  Thanks for the info!
